### ISSUE TITLE
REL: 1.4

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-examples#209]
We should make a 1.4 release of bids-examples to mark the 1.4 release of the bids-specification (for "common derivatives).

I started a milestone: https://github.com/bids-standard/bids-examples/milestone/1

I propose that we do this release once:
- [x] CI ~passes~ issues are partially addressed (need to do several fixes: #214)
- [x] derivatives example is merged (#201 )
- [x] CI enhancement is merged (#207)

**Comment by sappelhoff** [comment]
done: https://github.com/bids-standard/bids-examples/releases/tag/1.4.0
